### ISSUE TITLE
run.go: runtime error

### ISSUE THREAD

**Issue by schu** [kinvolk/kube-spawn#183]
```
panic: runtime error: index out of range

goroutine 7 [running]:
github.com/kinvolk/kube-spawn/pkg/nspawntool.Run(0xc4202ce000, 0x2, 0x0, 0x0)
        /go/src/github.com/kinvolk/kube-spawn/pkg/nspawntool/run.go:39 +0x1192
main.doStart.func1(0xc420301060, 0xc4202ce000, 0x2)
        /go/src/github.com/kinvolk/kube-spawn/cmd/kube-spawn/start.go:72 +0x12c
created by main.doStart
        /go/src/github.com/kinvolk/kube-spawn/cmd/kube-spawn/start.go:82 +0x262
```

To reproduce, create a new environment, start it, stop it, change the number of nodes from 2 to 3, start it again.

**Comment by schu** [comment]
I'm not sure this should be supported. Either way, it shouldn't panic.
